env:
  browser: true
  es2021: true
extends: standard
globals:
  # k6 提供的内置变量
  __ENV: readonly
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 4
  camelcase: 0
  comma-dangle:
    - error
    - only-multiline
