# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=2048]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
        args:
          - --quiet
      - id: djlint-django
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-rc.0
    hooks:
      - id: eslint
        args:
          - --fix
        additional_dependencies:
          - eslint@^8.0.1
          - eslint-config-standard@latest
          - eslint-plugin-import@^2.25.2
          - eslint-plugin-n@^15.0.0 || ^16.0.0
          - eslint-plugin-promise@^6.0.0
  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos

exclude: "^contest/quiz/migrations/.+\\.py$"
