# Generated by Django 4.1.2 on 2022-10-30 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_student_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "回答", "verbose_name_plural": "回答"},
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "选项", "verbose_name_plural": "选项"},
        ),
        migrations.AlterModelOptions(
            name="draftanswer",
            options={"verbose_name": "回答草稿", "verbose_name_plural": "回答草稿"},
        ),
        migrations.AlterModelOptions(
            name="draftresponse",
            options={"verbose_name": "答卷草稿", "verbose_name_plural": "答卷草稿"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "题目", "verbose_name_plural": "题目"},
        ),
        migrations.AlterModelOptions(
            name="response",
            options={"verbose_name": "答卷", "verbose_name_plural": "答卷"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "学生", "verbose_name_plural": "学生"},
        ),
        migrations.AddField(
            model_name="response",
            name="submit_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="提交时刻"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="choice",
            name="content",
            field=models.CharField(max_length=200, verbose_name="选项内容"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="correct",
            field=models.BooleanField(verbose_name="是否应选"),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.CharField(max_length=200, verbose_name="题干内容"),
        ),
        migrations.AlterField(
            model_name="response",
            name="score",
            field=models.FloatField(verbose_name="得分"),
        ),
        migrations.AlterField(
            model_name="student",
            name="final_score",
            field=models.FloatField(verbose_name="最终得分"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=50, verbose_name="姓名"),
        ),
    ]
