# Generated by Django 4.1.2 on 2022-10-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_answer_options_alter_choice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftanswer",
            name="choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.choice",
            ),
        ),
    ]
