# Generated by Django 4.1.2 on 2022-10-30 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_draftanswer_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftresponse",
            name="deadline",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="截止时刻"
            ),
            preserve_default=False,
        ),
    ]
