# Generated by Django 4.1.2 on 2022-10-30 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "quiz",
            "0005_alter_draftanswer_choice_squashed_0007_alter_draftresponse_student",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.choice",
                verbose_name="所选选项",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
                verbose_name="题干",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.response",
                verbose_name="答卷",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
                verbose_name="题干",
            ),
        ),
        migrations.AlterField(
            model_name="draftanswer",
            name="choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.choice",
                verbose_name="所选选项",
            ),
        ),
        migrations.AlterField(
            model_name="draftanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
                verbose_name="题干",
            ),
        ),
        migrations.AlterField(
            model_name="draftanswer",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.draftresponse",
                verbose_name="答卷",
            ),
        ),
        migrations.AlterField(
            model_name="draftresponse",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.student",
                verbose_name="作答者",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.student",
                verbose_name="作答者",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
