# Generated by Django 4.1.2 on 2022-10-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("quiz", "0009_remove_response_score"),
        ("quiz", "0010_remove_student_final_score"),
    ]

    dependencies = [
        ("quiz", "0008_alter_answer_choice_alter_answer_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="score",
        ),
        migrations.RemoveField(
            model_name="student",
            name="final_score",
        ),
    ]
