# Generated by Django 4.2.17 on 2026-09-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftresponse",
            name="deadline",
            field=models.DateTimeField(db_index=True, verbose_name="截止时刻"),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("R", "单项选择"), ("B", "判断")],
                db_index=True,
                max_length=1,
                verbose_name="类型",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="submit_at",
            field=models.DateTimeField(db_index=True, verbose_name="提交时刻"),
        ),
    ]
